#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] ; then
    db_get openstack-proxy-node/create_endpoints || true
    if [ "$RET" = "true" ] ; then
	db_get openstack-proxy-node/region || true
	REGION=$RET
	db_get openstack-proxy-node/ip_address || true
	IP=$RET
	
	/usr/share/openstack-proxy-node/openstack-proxy-node-create-endpoints "$IP" "$REGION"
    fi
    db_stop
fi
    
#DEBHELPER#
