#!/bin/sh

set -e

apt-get -y purge python-all python-setuptools-git python-sphinx \
python-nosexcover python-eventlet python-iso8601 python-keyring python-cmd2 \
python-pyparsing python-py python-virtualenv python-amqplib python-anyjson \
python-configobj python-gflags pylint python-ldap python-memcache \
python-migrate python-pam python-passlib python-paste python-pastedeploy \
python-routes python-webob python-webtest sqlite3 python-boto python-crypto \
python-kombu python-xattr python-netifaces python-openssl bpython euca2ools \
ipython python-babel python-carrot python-cheetah python-distutils-extra \
python-feedparser python-libvirt python-lockfile python-netaddr \
python-paramiko python-qpid python-suds python-xenapi python-sqlite \
python-pyudev python-requests python-daemon python-libxml2 python-pycurl \
python-sqlalchemy-ext python-mysqldb python-django-nose \
node-less python-dev python-mock pep8 python-prettytable python-jsonschema \
python-httplib2 python-mox python-simplejson python-unittest2 python-lxml \
curl python-all-dev python-flask python-ming python-stevedore libvirt-bin \
python-pecan python-extras python-warlock \
apache2 apache2-mpm-worker apache2-utils apache2.2-bin \
apache2.2-common binutils ca-certificates cinder-api cinder-common \
cinder-scheduler cpp cpp-4.6 cpp-4.7 dkms erlang-asn1 erlang-base \
erlang-corba erlang-crypto erlang-diameter erlang-edoc erlang-eldap \
erlang-erl-docgen erlang-eunit erlang-ic erlang-inets erlang-inviso \
erlang-mnesia erlang-nox erlang-odbc erlang-os-mon erlang-parsetools \
erlang-percept erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssh \
erlang-ssl erlang-syntax-tools erlang-tools erlang-webtool erlang-xmerl \
fakeroot file gcc gcc-4.6 gcc-4.6-base gcc-4.7 glance glance-api \
glance-common glance-registry heirloom-mailx javascript-common keystone less \
libapache2-mod-wsgi libapr1 libaprutil1 libaprutil1-dbd-sqlite3 \
libaprutil1-ldap libc-ares2 libc-dev-bin libc6-dev \
libev4 libevent-2.0-5 libgmp10 \
libgomp1 libhtml-template-perl libitm1 libjs-jquery libjs-jquery-cookie \
libjs-jquery-metadata libjs-jquery-tablesorter libjs-mochikit \
libjs-sphinxdoc libjs-underscore libltdl7 libmagic1 libmpc2 \
libmpfr4 libodbc1 libopts25 \
libplrpc-perl libpython2.6 libpython2.7 libquadmath0 \
libsasl2-modules libsctp1 libsqlite0 libv8-3.8.9.20 libxslt1.1 \
libyaml-0-2 linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common \
linux-headers-amd64 linux-kbuild-3.2 linux-libc-dev lksctp-tools make \
manpages-dev memcached mime-support \
nova-api nova-common nova-scheduler nova-xvpvncproxy ntp openssl \
openstack-cloud-identity openstack-cloud-services openstack-dashboard \
openstack-dashboard-apache openstack-pkg-tools openstack-proxy-node \
openvswitch-common openvswitch-datapath-dkms openvswitch-switch patch pep8 \
python python-amqplib python-anyjson python-appconf python-babel \
python-boto python-carrot python-cheetah python-cinder python-cinderclient \
python-cliff python-cloudfiles python-cmd2 python-compressor \
python-configobj python-coverage python-crypto python-daemon python-dateutil \
python-decorator python-dingus python-django python-django-horizon \
python-django-nose python-dns python-eventlet python-formencode \
python-gflags python-glance python-glanceclient python-greenlet \
python-httplib2 python-iso8601 python-jsonschema python-keyring \
python-keystone python-keystoneclient python-kombu python-ldap \
python-libxml2 python-lockfile python-lxml python-m2crypto python-memcache \
python-migrate python-minimal python-mock python-mysqldb python-netaddr \
python-netifaces python-nose python-nova python-novaclient python-openid \
python-openssl python-openstack-auth python-pam python-paramiko \
python-passlib python-paste python-pastedeploy python-pastescript \
python-pkg-resources python-prettytable python-pycurl python-pyparsing \
python-pyudev python-quantum python-quantumclient python-repoze.lru \
python-routes python-scgi python-setuptools python-setuptools-git \
python-simplejson python-sqlalchemy python-sqlalchemy-ext python-sqlite \
python-stompy python-suds python-support python-swift python-swiftclient \
python-tempita python-tz python-warlock python-webob python-xattr \
python-yaml python2.6 python2.6-minimal python2.7 python2.7-minimal \
quantum-common quantum-plugin-openvswitch quantum-server rabbitmq-server \
rsync sqlite3 ssl-cert uuid-runtime wwwconfig-common \
dnsmasq dnsmasq-base dnsmasq-utils

apt-get -y purge mysql-server mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-common libmysqlclient18 \
	libaio1 libdbd-mysql-perl libdbi-perl libnet-daemon-perl libplrpc-perl psmisc

apt-get -y --purge autoremove
