#!/bin/sh

set -e

apt-get -y purge nova-common neutron-common ceilometer-common cinder-common glance-common heat-common
apt-get -y purge keystone

apt-get -y purge python-all python-setuptools-git python-sphinx \
python-nosexcover python-eventlet python-iso8601 python-keyring python-cmd2 \
python-pyparsing python-py python-virtualenv python-amqplib python-anyjson \
python-configobj python-gflags pylint python-ldap python-memcache \
python-migrate python-pam python-passlib python-paste python-pastedeploy \
python-routes python-webob python-webtest sqlite3 python-boto python-crypto \
python-kombu python-xattr python-netifaces python-openssl bpython euca2ools \
ipython python-babel python-carrot python-cheetah python-distutils-extra \
python-feedparser python-libvirt python-lockfile python-netaddr \
python-paramiko python-qpid python-suds python-xenapi python-sqlite \
python-pyudev python-requests python-daemon python-libxml2 python-pycurl \
python-sqlalchemy-ext python-mysqldb python-django-nose \
python-dev python-mock pep8 python-prettytable python-jsonschema \
python-httplib2 python-mox python-simplejson python-unittest2 python-lxml \
curl python-all-dev python-flask python-ming python-stevedore libvirt-bin \
python-pecan python-extras python-warlock \
apache2 apache2-mpm-worker apache2-utils apache2.2-bin \
apache2.2-common binutils ca-certificates \
cpp cpp-4.6 cpp-4.7 dkms erlang-asn1 erlang-base \
erlang-corba erlang-crypto erlang-diameter erlang-edoc erlang-eldap \
erlang-erl-docgen erlang-eunit erlang-ic erlang-inets erlang-inviso \
erlang-mnesia erlang-nox erlang-odbc erlang-os-mon erlang-parsetools \
erlang-percept erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssh \
erlang-ssl erlang-syntax-tools erlang-tools erlang-webtool erlang-xmerl \
fakeroot file gcc gcc-4.6 gcc-4.6-base gcc-4.7 glance glance-api \
glance-common glance-registry heirloom-mailx javascript-common keystone less \
libapache2-mod-wsgi libapr1 libaprutil1 libaprutil1-dbd-sqlite3 \
libaprutil1-ldap libc-ares2 libc-dev-bin libc6-dev \
libev4 libevent-2.0-5 libgmp10 \
libgomp1 libhtml-template-perl libitm1 libjs-jquery libjs-jquery-cookie \
libjs-jquery-metadata libjs-jquery-tablesorter libjs-mochikit \
libjs-sphinxdoc libjs-underscore libltdl7 libmagic1 libmpc2 \
libmpfr4 libodbc1 libopts25 \
libpython2.6 libpython2.7 libquadmath0 \
libsasl2-modules libsctp1 libsqlite0 libv8-3.8.9.20 libxslt1.1 \
libyaml-0-2 linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common \
linux-headers-amd64 linux-kbuild-3.2 linux-libc-dev lksctp-tools make \
manpages-dev memcached \
nova-api nova-scheduler nova-xvpvncproxy ntp \
openstack-cloud-identity openstack-cloud-services openstack-dashboard \
openstack-dashboard-apache openstack-pkg-tools openstack-proxy-node \
patch pep8 \
python-amqplib python-anyjson python-appconf python-babel \
python-boto python-carrot python-cheetah python-cinder python-cinderclient \
python-cliff python-cloudfiles python-cmd2 python-compressor \
python-configobj python-coverage python-crypto python-daemon python-dateutil \
python-decorator python-dingus python-django python-django-horizon \
python-django-nose python-dns python-eventlet python-formencode \
python-gflags python-glance python-glanceclient python-greenlet \
python-httplib2 python-iso8601 python-jsonschema python-keyring \
python-keystone python-keystoneclient python-kombu python-ldap \
python-libxml2 python-lockfile python-lxml python-m2crypto python-memcache \
python-migrate python-mock python-mysqldb python-netaddr \
python-netifaces python-nose python-nova python-novaclient python-openid \
python-openssl python-openstack-auth python-pam python-paramiko \
python-passlib python-paste python-pastedeploy python-pastescript \
python-pkg-resources python-prettytable python-pycurl python-pyparsing \
python-pyudev python-quantum python-quantumclient python-repoze.lru \
python-routes python-scgi python-setuptools python-setuptools-git \
python-simplejson python-sqlalchemy python-sqlalchemy-ext python-sqlite \
python-stompy python-suds python-support python-swift python-swiftclient \
python-tempita python-tz python-warlock python-webob python-xattr \
python-yaml python2.6 python2.6-minimal \
quantum-common quantum-plugin-openvswitch quantum-server rabbitmq-server \
rsync sqlite3 ssl-cert wwwconfig-common \
dnsmasq dnsmasq-base dnsmasq-utils \
augeas-lenses btrfs-tools cryptsetup cryptsetup-bin dbus docutils-common docutils-doc ebtables febootstrap fontconfig-config fonts-droid \
ghostscript gsfonts html2text ipxe-qemu jfsutils kpartx libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl \
libasound2 libasyncns0 libaugeas0 libavahi-client3 libavahi-common-data libavahi-common3 libbluetooth3 libboost-filesystem1.49.0 \
libboost-program-options1.49.0 libboost-system1.49.0 libboost-thread1.49.0 libbrlapi0.5 libcaca0 libcap-ng0 libcap2 libconfig9 libcroco3 \
libcryptsetup4 libcups2 libcupsimage2 libcurl3 libcurl3-gnutls libdbus-1-3 libdirectfb-1.2-9 libdpkg-perl libencode-locale-perl \
liberror-perl libffi5 libfile-listing-perl libflac8 libfont-afm-perl libfontconfig1 libgettextpo0 libglib2.0-0 libgs9 libgs9-common \
libhivex0 libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl \
libhttp-daemon-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl libice6 libicu48 libijs-0.35 libio-socket-ip-perl \
libio-socket-ssl-perl libiscsi1 libjasper1 libjbig2dec0 libjpeg8 libjson0 liblcms1 liblcms2-2 liblwp-mediatypes-perl libmailtools-perl \
libnet-http-perl libnet-ssleay-perl libnetfilter-conntrack3 libnetpbm10 libnl1 libnuma1 libogg0 libpaper-utils libpaper1 libpcap0.8 \
libpciaccess0 libpcrecpp0 libpixman-1-0 libpulse0 librabbitmq1 librtmp0 libsdl1.2debian libsm6 libsndfile1 libsocket-perl \
libspice-server1 libssh2-1 libsysfs2 libsystemd-login0 libtidy-0.99-0 libtiff4 libtimedate-perl libts-0.0-0 libunistring0 \
liburi-perl libusbredirparser0 libvdeplug2 libvorbis0a libvorbisenc2 libwww-robotrules-perl libx11-xcb1 libxenstore3.0 \
libxi6 libxml2 libxml2-dev libxml2-utils libxtst6 libyajl2 lsof mongodb-clients mongodb-server netcat-openbsd netpbm ntfs-3g \
open-iscsi poppler-data qemu-keymaps reiserfsprogs scrub seabios sgml-base sharutils strace tsconf ttf-dejavu-core vgabios \
vlan x11-common xfsprogs xml-core zerofree

apt-get -y purge mysql-server mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-common libmysqlclient18 \
	libaio1 libdbd-mysql-perl libdbi-perl libnet-daemon-perl libplrpc-perl psmisc

apt-get -y --purge autoremove
